<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="5033" started-at="2016-04-01T17:16:11Z" finished-at="2016-04-01T17:16:16Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="5033" started-at="2016-04-01T17:16:11Z" finished-at="2016-04-01T17:16:16Z">
      <class name="Tests.TestAnonymousUser">
        <test-method status="FAIL" signature="AnonymousUserWorkflow()[pri:0, instance:Tests.TestAnonymousUser@43a25848]" name="AnonymousUserWorkflow" duration-ms="16" started-at="2016-04-01T13:16:11Z" finished-at="2016-04-01T13:16:11Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at Utilities.TestRoot.findElement(TestRoot.java:227)
	at Utilities.TestRoot.waitForVisible(TestRoot.java:249)
	at Behavior.AnonymousUser.clickMayBeLater(AnonymousUser.java:11)
	at Tests.TestAnonymousUser.AnonymousUserWorkflow(TestAnonymousUser.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AnonymousUserWorkflow -->
        <test-method status="PASS" signature="after()[pri:0, instance:Tests.TestAnonymousUser@43a25848]" name="after" is-config="true" duration-ms="5006" started-at="2016-04-01T13:16:11Z" finished-at="2016-04-01T13:16:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- after -->
      </class> <!-- Tests.TestAnonymousUser -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
